In [98]:
from google.colab import drive # remove the cell if not using colab
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [99]:
import pandas as pd
import numpy as np
from pathlib import Path
base_path = Path('/content/drive/MyDrive/solvro_dane') # change path here!

# Klasyfikacja pasażerów Titanica
Nie wiemy czy dla DiCaprio było miejsce na drzwiach, ale wiemy że grdyby był tam Wojfer87 to by z nimi wyciskał pompki na górze lodowej. Teraz twoja pora na wyciskanie.
#Twoje zadnie to:
**stworzenie modelu przewidującego szanse przeżycia katastrofy Titanica**.

![https://i1.jbzd.com.pl/contents/2025/11/normal/v5Fth4DcPpPPxSrXQ5rCbAgZ8EifWiiF.png](https://i1.jbzd.com.pl/contents/2025/11/normal/v5Fth4DcPpPPxSrXQ5rCbAgZ8EifWiiF.png "Wojfer")


#### Twoim celem będzie jest wytrenowanie modeli do klasyfikacji każdego pasażera Titanica jako ofiary (0) lub osoby, która przeżyła (1).

Poniżej znajdziesz pytania, które mogą być pomocne w zadaniu:

- Czego nauczyło Cię o badanym zbiorze danych poprzednie zadanie? Jak możesz wykorzystać wyciągnięte z niego wnioski w procesie tworzenia modelu?
- Jak przeprowadzenie standaryzacji danych może wpływać na zachowanie modelu?
- Co mój model robi i w jaki sposób?
- Jak nie przetrenować wybranego modelu?
- Jaki wynik klasyfikacji możemy uznać za *dobry*?


Wymagania:
- Wypisz obserwacje z pierwszego zadania, które pomogą Ci w tym. Co było przydatne, a co okazało się bezużyteczne?
- [Nie doprowadź](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) do ~~przecieku statku~~ wycieku danych (np. nie ucz modelu na danych testowych). Nauczone modele odpal na danych treningowych i testowych - opisz uzyskane wyniki.
- Stwórz baseline, czyli dla porównania sprawdź jak z zadaniem radzi sobie [Dummy Classifier](https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyClassifier.html) (jeśli Twój docelowy model radzi sobie gorzej - uciekaj)
- Przeprowadź badania na dwóch wybranych modelach uczenia maszynowego (np. spośród: drzew decyzyjnych, SVM, MLP, KNN, z gwiazdką [XGBoost](https://xgboost.readthedocs.io/en/stable))
- W badaniach użyj wybranych metryk. Wybór uzasadnij.
- Dla każdego modelu wybierz co najmniej dwa hiperparametry i przeprowadź badania zależności wyników metryk od wartości hiperparametrów. Zwizualizuj wszystko ładnie, zastanów się dlaczego tak mogło być i wyciągnij i wypisz wnioski.
- Podsumuj przeprowadzone badania, wypisz wnioski.

Niezmiennie, zadbaj o czytelność kodu i nazewnictwo zmiennych. Jeśli jakiś wycinek kodu się powtarza, to wyodrębnij go do funkcji. Postaraj się zamieszczać swoje wnioski w postaci komentarza `Markdown`.

Jeśli chcesz, możesz sprawdzić (przyjmując pewne założenia), jakie byłyby Twoje szanse na Titanicu.

Uwaga! Jeśli Titanic to dla Ciebie nic i baaaaardzo chcesz to możesz w ramach tego zadania zająć się [bardziej wymagającym](https://archive.ics.uci.edu/dataset/365/polish+companies+bankruptcy+data) zbiorem.

In [100]:
titanic_df = pd.read_csv(base_path / 'titanic_final.csv', index_col='PassengerId')

# Wnioski z EDA
Większą szansę na przeżycie miały:
* kobiety
* dzieci
* pasażerowie wyższych klas
* pasażerowie z przypisanymi kabinami (łączy się z klasą)

# Ładowanie i dzielenie danych

In [101]:
from sklearn.model_selection import train_test_split

X = titanic_df.drop(columns=['Survived'])
y = titanic_df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=.8, shuffle=True)

# Skalowanie danych

In [102]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Baseline - Dummy Classifier

In [103]:
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support, classification_report
from sklearn.dummy import DummyClassifier

model = DummyClassifier(strategy='most_frequent') # dane nie są zbalansowane - większość zginęła
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(classification_report(y_test, y_pred))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0       0.60      1.00      0.75       107
           1       0.00      0.00      0.00        72

    accuracy                           0.60       179
   macro avg       0.30      0.50      0.37       179
weighted avg       0.36      0.60      0.45       179

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

array([[107,   0],
       [ 72,   0]])

# Support Vector Machine

In [104]:
from sklearn.svm import SVC

svm = SVC(kernel='linear')  # liniowe SVM
svm.fit(X_train_scaled, y_train)

y_pred = svm.predict(X_test_scaled)

print(classification_report(y_test, y_pred))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0       0.81      0.91      0.85       107
           1       0.83      0.68      0.75        72

    accuracy                           0.82       179
   macro avg       0.82      0.79      0.80       179
weighted avg       0.82      0.82      0.81       179

array([[97, 10],
       [23, 49]])

# Multi Layer Perceptron

In [105]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(max_iter=1000, random_state=42, hidden_layer_sizes=(64, 32), early_stopping=True)
mlp.fit(X_train_scaled, y_train)

y_pred = mlp.predict(X_test_scaled)

print(classification_report(y_test, y_pred))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0       0.78      0.94      0.86       107
           1       0.88      0.61      0.72        72

    accuracy                           0.81       179
   macro avg       0.83      0.78      0.79       179
weighted avg       0.82      0.81      0.80       179

array([[101,   6],
       [ 28,  44]])

# K Nearest Neighbors

In [106]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=10, metric='cosine')
knn.fit(X_train_scaled, y_train)

y_pred = knn.predict(X_test_scaled)

print(classification_report(y_test, y_pred))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0       0.77      0.95      0.85       107
           1       0.89      0.57      0.69        72

    accuracy                           0.80       179
   macro avg       0.83      0.76      0.77       179
weighted avg       0.82      0.80      0.79       179

array([[102,   5],
       [ 31,  41]])

W zależności od tego jak załadują się dane, modele dają znacząco różne wyniki.

# Cross-Validation

In [107]:
from sklearn.model_selection import cross_val_score

svm_score = cross_val_score(svm, X, y, cv=5, scoring='f1')
mlp_score = cross_val_score(mlp, X, y, cv=5, scoring='f1')
knn_score = cross_val_score(knn, X, y, cv=5, scoring='f1')

print('---------- SVM ----------')
print(svm_score)
print(f"srednia: {svm_score.mean():.3f}  odchylenie: {svm_score.std():.3f}")

print('\n---------- MLP ----------')
print(mlp_score)
print(f"srednia: {mlp_score.mean():.3f}  odchylenie: {mlp_score.std():.3f}")

print('\n---------- KNN ----------')
print(knn_score)
print(f"srednia: {knn_score.mean():.3f}  odchylenie: {knn_score.std():.3f}")

---------- SVM ----------
[0.7826087  0.76691729 0.75384615 0.70588235 0.82089552]
srednia: 0.766  odchylenie: 0.038

---------- MLP ----------
[0.38655462 0.55932203 0.50485437 0.59459459 0.56198347]
srednia: 0.521  odchylenie: 0.073

---------- KNN ----------
[0.58015267 0.64       0.59016393 0.61016949 0.60714286]
srednia: 0.606  odchylenie: 0.020

Wybrałem metrykę f1 - jest ona harmoniczną średnią z precision i recall. Model musi dobrze wybierać, ale też nie może się za często mylić. Z obecnymi parametrami dość często się myli.

In [108]:
!pip install optuna
import optuna
from sklearn.pipeline import Pipeline
import optuna.visualization as vis

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.19.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)

# Szukanie hiperparametrów dla SVM

In [109]:
def svm_search(trial):
  c_param = trial.suggest_float('C', 0.01, 100, log=True)

  kernel_param = trial.suggest_categorical('kernel', ['linear', 'rbf'])

  if kernel_param == 'rbf':
      gamma_param = trial.suggest_float('gamma', 0.0001, 10, log=True)
  else:
      gamma_param = 'scale'

  class_weight_param = trial.suggest_categorical('class_weight', [None, 'balanced'])

  svm = SVC(C=c_param, kernel=kernel_param, gamma=gamma_param,
            class_weight=class_weight_param, random_state=42)

  pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('svm', svm)
    ])

  score = cross_val_score(pipeline, X, y, cv=5, scoring='f1').mean()
  return score

study = optuna.create_study(direction='maximize')

study.optimize(svm_search, n_trials=100)

print("\n--- ZAKOŃCZONO ---")
print(f"Najlepsze Accuracy: {study.best_value:.4f}")
print("Najlepsze parametry:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

[I 2026-08-15 21:57:43,085] A new study created in memory with name: no-name-898c334e-1231-4322-b546-7c85ee6a5789
[I 2026-08-15 21:57:43,391] Trial 0 finished with value: 0.554738530342075 and parameters: {'C': 0.022441225976441985, 'kernel': 'rbf', 'gamma': 0.00017489421144158533, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.554738530342075.
[I 2026-08-15 21:57:53,743] Trial 1 finished with value: 0.7611249092863348 and parameters: {'C': 75.89235433840862, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7611249092863348.
[I 2026-08-15 21:57:54,888] Trial 2 finished with value: 0.7571556987788333 and parameters: {'C': 30.569113036668178, 'kernel': 'rbf', 'gamma': 0.011148870472313362, 'class_weight': None}. Best is trial 1 with value: 0.7611249092863348.
[I 2026-08-15 21:57:55,860] Trial 3 finished with value: 0.7585145709314981 and parameters: {'C': 2.632384441417451, 'kernel': 'rbf', 'gamma': 0.004694764429246701, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7611249092863348.
[I 2026-08-15 21:58:01,813] Trial 4 finished with value: 0.7622868741159285 and parameters: {'C': 21.914292209003623, 'kernel': 'linear', 'class_weight': None}. Best is trial 4 with value: 0.7622868741159285.
[I 2026-08-15 21:58:02,309] Trial 5 finished with value: 0.0 and parameters: {'C': 0.08655464804490562, 'kernel': 'rbf', 'gamma': 0.0011880391245560563, 'class_weight': None}. Best is trial 4 with value: 0.7622868741159285.
[I 2026-08-15 21:58:02,896] Trial 6 finished with value: 0.7276956821799023 and parameters: {'C': 73.05196494410573, 'kernel': 'rbf', 'gamma': 0.10455031325938142, 'class_weight': None}. Best is trial 4 with value: 0.7622868741159285.
[I 2026-08-15 21:58:03,402] Trial 7 finished with value: 0.6530795507585803 and parameters: {'C': 0.18269391262933957, 'kernel': 'rbf', 'gamma': 5.415319536156994, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.7622868741159285.
[I 2026-08-15 21:58:03,736] Trial 8 finished with value: 0.7591534771978482 and parameters: {'C': 0.625888357889276, 'kernel': 'rbf', 'gamma': 0.019533879711602652, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.7622868741159285.
[I 2026-08-15 21:58:04,083] Trial 9 finished with value: 0.7448463379980946 and parameters: {'C': 28.961723506573513, 'kernel': 'rbf', 'gamma': 0.00022356325933584143, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.7622868741159285.
[I 2026-08-15 21:58:05,165] Trial 10 finished with value: 0.7641497402364538 and parameters: {'C': 2.8600220337088564, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:06,067] Trial 11 finished with value: 0.7641497402364538 and parameters: {'C': 4.281195941979333, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:06,795] Trial 12 finished with value: 0.7641497402364538 and parameters: {'C': 3.2787480528432087, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:07,412] Trial 13 finished with value: 0.7641497402364538 and parameters: {'C': 2.508313992146377, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:09,614] Trial 14 finished with value: 0.7641497402364538 and parameters: {'C': 6.9532780875822775, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:10,389] Trial 15 finished with value: 0.7641497402364538 and parameters: {'C': 0.6308885778467889, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:11,126] Trial 16 finished with value: 0.7641497402364538 and parameters: {'C': 0.7518978737144802, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:14,099] Trial 17 finished with value: 0.7622868741159285 and parameters: {'C': 10.335919860280738, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:14,724] Trial 18 finished with value: 0.7629533294687569 and parameters: {'C': 1.2387026614685703, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:14,998] Trial 19 finished with value: 0.761808427858739 and parameters: {'C': 0.1560692242316915, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:16,212] Trial 20 finished with value: 0.7641497402364538 and parameters: {'C': 7.038150504081728, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:16,946] Trial 21 finished with value: 0.7641497402364538 and parameters: {'C': 2.4533557033373694, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:17,921] Trial 22 finished with value: 0.7641497402364538 and parameters: {'C': 3.4966528634812426, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:19,942] Trial 23 finished with value: 0.7641497402364538 and parameters: {'C': 12.37490975971535, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:20,322] Trial 24 finished with value: 0.7629533294687569 and parameters: {'C': 1.3001562509732156, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:20,493] Trial 25 finished with value: 0.7629533294687569 and parameters: {'C': 0.32329257344305345, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:21,042] Trial 26 finished with value: 0.7641497402364538 and parameters: {'C': 6.005882026722225, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:21,281] Trial 27 finished with value: 0.7629533294687569 and parameters: {'C': 1.2960845538007342, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:21,661] Trial 28 finished with value: 0.7641497402364538 and parameters: {'C': 3.8400269622501213, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:21,798] Trial 29 finished with value: 0.7538722381653142 and parameters: {'C': 0.01586479913469308, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:21,937] Trial 30 finished with value: 0.7538059394016894 and parameters: {'C': 0.05360006768019374, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:22,215] Trial 31 finished with value: 0.7641497402364538 and parameters: {'C': 1.9625625405507219, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:23,276] Trial 32 finished with value: 0.7622868741159285 and parameters: {'C': 14.809971065901099, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:23,665] Trial 33 finished with value: 0.7641497402364538 and parameters: {'C': 4.446490007705374, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:23,940] Trial 34 finished with value: 0.762281405349327 and parameters: {'C': 1.8754571460193092, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:24,104] Trial 35 finished with value: 0.7629533294687569 and parameters: {'C': 0.36496570721768995, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:25,960] Trial 36 finished with value: 0.7622868741159285 and parameters: {'C': 18.789422034551805, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:26,627] Trial 37 finished with value: 0.681837850006864 and parameters: {'C': 59.90850002244289, 'kernel': 'rbf', 'gamma': 3.6859683927508153, 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:27,183] Trial 38 finished with value: 0.762281405349327 and parameters: {'C': 2.948512445125227, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:27,542] Trial 39 finished with value: 0.7297184186871994 and parameters: {'C': 8.748543186335532, 'kernel': 'rbf', 'gamma': 0.35400420208482886, 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:31,089] Trial 40 finished with value: 0.7622868741159285 and parameters: {'C': 38.76414076792537, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:31,531] Trial 41 finished with value: 0.7641497402364538 and parameters: {'C': 5.5870149701767255, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:32,073] Trial 42 finished with value: 0.7641497402364538 and parameters: {'C': 7.330708458214404, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:32,334] Trial 43 finished with value: 0.7629533294687569 and parameters: {'C': 1.5530304591250725, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:32,690] Trial 44 finished with value: 0.7641497402364538 and parameters: {'C': 4.258808804521872, 'kernel': 'linear', 'class_weight': None}. Best is trial 10 with value: 0.7641497402364538.
[I 2026-08-15 21:58:32,884] Trial 45 finished with value: 0.7641955720746463 and parameters: {'C': 0.9887782237899992, 'kernel': 'rbf', 'gamma': 0.39085423186566653, 'class_weight': 'balanced'}. Best is trial 45 with value: 0.7641955720746463.
[I 2026-08-15 21:58:33,079] Trial 46 finished with value: 0.7551343316627861 and parameters: {'C': 0.9265898767865622, 'kernel': 'rbf', 'gamma': 0.5213013476610505, 'class_weight': 'balanced'}. Best is trial 45 with value: 0.7641955720746463.
[I 2026-08-15 21:58:33,272] Trial 47 finished with value: 0.7534654032448855 and parameters: {'C': 0.3453332924392314, 'kernel': 'rbf', 'gamma': 0.07386414178668038, 'class_weight': 'balanced'}. Best is trial 45 with value: 0.7641955720746463.
[I 2026-08-15 21:58:33,501] Trial 48 finished with value: 0.7277025781098595 and parameters: {'C': 0.5067270207666963, 'kernel': 'rbf', 'gamma': 1.117098477314269, 'class_weight': 'balanced'}. Best is trial 45 with value: 0.7641955720746463.
[I 2026-08-15 21:58:33,684] Trial 49 finished with value: 0.714920882170875 and parameters: {'C': 0.8500513755793873, 'kernel': 'rbf', 'gamma': 0.0015861303093889698, 'class_weight': 'balanced'}. Best is trial 45 with value: 0.7641955720746463.
[I 2026-08-15 21:58:33,863] Trial 50 finished with value: 0.7688748351822462 and parameters: {'C': 1.9232297026512597, 'kernel': 'rbf', 'gamma': 0.07757320966787276, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:34,048] Trial 51 finished with value: 0.7659492831266902 and parameters: {'C': 2.357739314469017, 'kernel': 'rbf', 'gamma': 0.08579173682349114, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:34,236] Trial 52 finished with value: 0.7581073560974976 and parameters: {'C': 2.372404180685791, 'kernel': 'rbf', 'gamma': 0.11293773011369986, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:34,437] Trial 53 finished with value: 0.765659714517593 and parameters: {'C': 0.9794139357026231, 'kernel': 'rbf', 'gamma': 0.05045617352790787, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:34,611] Trial 54 finished with value: 0.7520602507533012 and parameters: {'C': 0.5058050335599281, 'kernel': 'rbf', 'gamma': 0.03193381945364372, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:34,806] Trial 55 finished with value: 0.7653373754402228 and parameters: {'C': 1.0242410820278853, 'kernel': 'rbf', 'gamma': 0.17972200376123965, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:35,004] Trial 56 finished with value: 0.7295211996986793 and parameters: {'C': 0.20644065602481107, 'kernel': 'rbf', 'gamma': 0.23342420762907629, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:35,193] Trial 57 finished with value: 0.7641374189512333 and parameters: {'C': 0.7525140259862266, 'kernel': 'rbf', 'gamma': 0.047700490288223284, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:35,419] Trial 58 finished with value: 0.7502277911859027 and parameters: {'C': 1.2822192849561467, 'kernel': 'rbf', 'gamma': 1.0118629728111979, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:35,602] Trial 59 finished with value: 0.7628487990332786 and parameters: {'C': 1.1195530356127068, 'kernel': 'rbf', 'gamma': 0.1749405296102426, 'class_weight': 'balanced'}. Best is trial 50 with value: 0.7688748351822462.
[I 2026-08-15 21:58:35,803] Trial 60 finished with value: 0.7691438887227731 and parameters: {'C': 1.8343069305151876, 'kernel': 'rbf', 'gamma': 0.05077393622267317, 'class_weight': 'balanced'}. Best is trial 60 with value: 0.7691438887227731.
[I 2026-08-15 21:58:35,981] Trial 61 finished with value: 0.7690485920033417 and parameters: {'C': 1.7270236178158422, 'kernel': 'rbf', 'gamma': 0.048375438552433904, 'class_weight': 'balanced'}. Best is trial 60 with value: 0.7691438887227731.
[I 2026-08-15 21:58:36,164] Trial 62 finished with value: 0.7671054969304757 and parameters: {'C': 1.7810353800645948, 'kernel': 'rbf', 'gamma': 0.04658816654340669, 'class_weight': 'balanced'}. Best is trial 60 with value: 0.7691438887227731.
[I 2026-08-15 21:58:36,349] Trial 63 finished with value: 0.7691438887227731 and parameters: {'C': 2.139454935554778, 'kernel': 'rbf', 'gamma': 0.042764748622626685, 'class_weight': 'balanced'}. Best is trial 60 with value: 0.7691438887227731.
[I 2026-08-15 21:58:36,545] Trial 64 finished with value: 0.7697862893607574 and parameters: {'C': 1.8596171379409667, 'kernel': 'rbf', 'gamma': 0.028934348822455033, 'class_weight': 'balanced'}. Best is trial 64 with value: 0.7697862893607574.
[I 2026-08-15 21:58:36,730] Trial 65 finished with value: 0.7705892627842827 and parameters: {'C': 2.5021616110917897, 'kernel': 'rbf', 'gamma': 0.01629436865377457, 'class_weight': 'balanced'}. Best is trial 65 with value: 0.7705892627842827.
[I 2026-08-15 21:58:36,915] Trial 66 finished with value: 0.7631615718946356 and parameters: {'C': 1.628701227780969, 'kernel': 'rbf', 'gamma': 0.013073407708432924, 'class_weight': 'balanced'}. Best is trial 65 with value: 0.7705892627842827.
[I 2026-08-15 21:58:37,097] Trial 67 finished with value: 0.769452383365427 and parameters: {'C': 1.8425267141043726, 'kernel': 'rbf', 'gamma': 0.023415260825387006, 'class_weight': 'balanced'}. Best is trial 65 with value: 0.7705892627842827.
[I 2026-08-15 21:58:37,290] Trial 68 finished with value: 0.7584535180408176 and parameters: {'C': 2.9641864670691955, 'kernel': 'rbf', 'gamma': 0.00676587018429601, 'class_weight': 'balanced'}. Best is trial 65 with value: 0.7705892627842827.
[I 2026-08-15 21:58:37,492] Trial 69 finished with value: 0.7517528387550936 and parameters: {'C': 0.5455559540461832, 'kernel': 'rbf', 'gamma': 0.021073024837027318, 'class_weight': 'balanced'}. Best is trial 65 with value: 0.7705892627842827.
[I 2026-08-15 21:58:37,688] Trial 70 finished with value: 0.7689555973202562 and parameters: {'C': 4.964382325782232, 'kernel': 'rbf', 'gamma': 0.026283668891546968, 'class_weight': 'balanced'}. Best is trial 65 with value: 0.7705892627842827.
[I 2026-08-15 21:58:37,870] Trial 71 finished with value: 0.771179681993573 and parameters: {'C': 3.5211241605584584, 'kernel': 'rbf', 'gamma': 0.02979699752170276, 'class_weight': 'balanced'}. Best is trial 71 with value: 0.771179681993573.
[I 2026-08-15 21:58:38,060] Trial 72 finished with value: 0.7658323226852234 and parameters: {'C': 5.1360118610552385, 'kernel': 'rbf', 'gamma': 0.022547583758320246, 'class_weight': 'balanced'}. Best is trial 71 with value: 0.771179681993573.
[I 2026-08-15 21:58:38,245] Trial 73 finished with value: 0.7728843247387478 and parameters: {'C': 3.453160371700084, 'kernel': 'rbf', 'gamma': 0.012023325437401387, 'class_weight': 'balanced'}. Best is trial 73 with value: 0.7728843247387478.
[I 2026-08-15 21:58:38,429] Trial 74 finished with value: 0.764548557002551 and parameters: {'C': 3.4989777851283943, 'kernel': 'rbf', 'gamma': 0.008217372356204561, 'class_weight': 'balanced'}. Best is trial 73 with value: 0.7728843247387478.
[I 2026-08-15 21:58:38,618] Trial 75 finished with value: 0.7688109612649553 and parameters: {'C': 2.390456802850858, 'kernel': 'rbf', 'gamma': 0.012517394286218663, 'class_weight': 'balanced'}. Best is trial 73 with value: 0.7728843247387478.
[I 2026-08-15 21:58:38,811] Trial 76 finished with value: 0.7585145709314981 and parameters: {'C': 3.538457950067358, 'kernel': 'rbf', 'gamma': 0.003568853785064853, 'class_weight': 'balanced'}. Best is trial 73 with value: 0.7728843247387478.
[I 2026-08-15 21:58:38,979] Trial 77 finished with value: 0.7631615718946356 and parameters: {'C': 1.5923062100764591, 'kernel': 'rbf', 'gamma': 0.013955807422884235, 'class_weight': 'balanced'}. Best is trial 73 with value: 0.7728843247387478.
[I 2026-08-15 21:58:39,164] Trial 78 finished with value: 0.7705153568503883 and parameters: {'C': 10.526305957217355, 'kernel': 'rbf', 'gamma': 0.00446255858349569, 'class_weight': 'balanced'}. Best is trial 73 with value: 0.7728843247387478.
[I 2026-08-15 21:58:39,342] Trial 79 finished with value: 0.7751435277934802 and parameters: {'C': 11.032118783737804, 'kernel': 'rbf', 'gamma': 0.005812683832505154, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.7751435277934802.
[I 2026-08-15 21:58:39,519] Trial 80 finished with value: 0.756717764738313 and parameters: {'C': 9.886281106228369, 'kernel': 'rbf', 'gamma': 0.00327478744178474, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.7751435277934802.
[I 2026-08-15 21:58:39,741] Trial 81 finished with value: 0.7727614137834592 and parameters: {'C': 16.25048958886117, 'kernel': 'rbf', 'gamma': 0.007129988047346017, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.7751435277934802.
[I 2026-08-15 21:58:40,072] Trial 82 finished with value: 0.7705734328585694 and parameters: {'C': 31.470454814214342, 'kernel': 'rbf', 'gamma': 0.005441721815402321, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.7751435277934802.
[I 2026-08-15 21:58:40,395] Trial 83 finished with value: 0.7698487951774099 and parameters: {'C': 29.76868073846788, 'kernel': 'rbf', 'gamma': 0.005325685203438727, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.7751435277934802.
[I 2026-08-15 21:58:40,726] Trial 84 finished with value: 0.7705734328585694 and parameters: {'C': 30.350145402145156, 'kernel': 'rbf', 'gamma': 0.005515615019073162, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.7751435277934802.
[I 2026-08-15 21:58:41,007] Trial 85 finished with value: 0.7727736195760864 and parameters: {'C': 36.81480300481307, 'kernel': 'rbf', 'gamma': 0.002397889533819585, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.7751435277934802.

--- ZAKOŃCZONO ---
Najlepsze Accuracy: 0.7751
Najlepsze parametry:
  C: 11.032118783737804
  kernel: rbf
  gamma: 0.005812683832505154
  class_weight: balanced

In [110]:
study.trials_dataframe().sort_values(by='value', ascending=False).head(10)

,number,value,datetime_start,datetime_complete,duration,params_C,params_class_weight,params_gamma,params_kernel,state
79,79,0.775144,2026-08-15 21:58:39.165525,2026-08-15 21:58:39.342871,0 days 00:00:00.177346,11.032119,balanced,0.005813,rbf,COMPLETE
90,90,0.773900,2026-08-15 21:58:42.199097,2026-08-15 21:58:42.524511,0 days 00:00:00.325414,57.485117,balanced,0.002379,rbf,COMPLETE
73,73,0.772884,2026-08-15 21:58:38.061622,2026-08-15 21:58:38.245094,0 days 00:00:00.183472,3.453160,balanced,0.012023,rbf,COMPLETE
85,85,0.772774,2026-08-15 21:58:40.727524,2026-08-15 21:58:41.007769,0 days 00:00:00.280245,36.814803,balanced,0.002398,rbf,COMPLETE
81,81,0.772761,2026-08-15 21:58:39.521020,2026-08-15 21:58:39.741569,0 days 00:00:00.220549,16.250490,balanced,0.007130,rbf,COMPLETE
71,71,0.771180,2026-08-15 21:58:37.689787,2026-08-15 21:58:37.870549,0 days 00:00:00.180762,3.521124,balanced,0.029797,rbf,COMPLETE
86,86,0.770980,2026-08-15 21:58:41.009924,2026-08-15 21:58:41.310581,0 days 00:00:00.300657,45.091312,balanced,0.002237,rbf,COMPLETE
65,65,0.770589,2026-08-15 21:58:36.546455,2026-08-15 21:58:36.730539,0 days 00:00:00.184084,2.502162,balanced,0.016294,rbf,COMPLETE
84,84,0.770573,2026-08-15 21:58:40.398086,2026-08-15 21:58:40.725937,0 days 00:00:00.327851,30.350145,balanced,0.005516,rbf,COMPLETE
82,82,0.770573,2026-08-15 21:58:39.742978,2026-08-15 21:58:40.071911,0 days 00:00:00.328933,31.470455,balanced,0.005442,rbf,COMPLETE

In [111]:
vis.plot_optimization_history(study)

In [112]:
vis.plot_param_importances(study)

In [113]:
vis.plot_parallel_coordinate(study)

# Szukanie hiperparametrów dla MLP

In [114]:
def mlp_search(trial):
  layer_options = {
        '32': (32,),
        '32_16': (32, 16),
        '64': (64,),
        '64_32': (64, 32),
        '128_64': (128, 64),
        '128_64_32': (128, 64, 32)
    }

  layer_name = trial.suggest_categorical('hidden_layer_sizes', list(layer_options.keys()))
  hidden_layer_sizes = layer_options[layer_name]

  activation = trial.suggest_categorical('activation', ['relu', 'tanh'])

  alpha = trial.suggest_float('alpha', 0.00001, 0.1, log=True)
  learning_rate_init = trial.suggest_float('learning_rate_init', 0.0001, 0.1, log=True)

  mlp = MLPClassifier(hidden_layer_sizes=hidden_layer_sizes, activation=activation, alpha=alpha,
                      learning_rate_init=learning_rate_init, max_iter=1000, random_state=42, early_stopping=True)

  pipeline = Pipeline([('scaler', StandardScaler()), ('mlp', mlp)])

  score = cross_val_score(pipeline, X, y, cv=5, scoring='f1').mean()

  return score

study = optuna.create_study(direction='maximize')

study.optimize(mlp_search, n_trials=100)

print("\n--- ZAKOŃCZONO ---")
print(f"Najlepsze Accuracy: {study.best_value:.4f}")
print("Najlepsze parametry:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

[I 2026-08-15 21:58:46,654] A new study created in memory with name: no-name-504e2547-54dc-4940-a7f0-a0910d83b681
[I 2026-08-15 21:58:54,925] Trial 0 finished with value: 0.7460158992907987 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 0.012029848457713642, 'learning_rate_init': 0.0011043990972873772}. Best is trial 0 with value: 0.7460158992907987.
[I 2026-08-15 21:58:56,858] Trial 1 finished with value: 0.7648515599116348 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.04043030079856312, 'learning_rate_init': 0.00879907482664625}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:58:59,359] Trial 2 finished with value: 0.7345050974902868 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 4.603360722978298e-05, 'learning_rate_init': 0.04099826932001915}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:59:01,933] Trial 3 finished with value: 0.1985090554181814 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 0.012861192450746501, 'learning_rate_init': 0.00019299920202494868}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:59:03,633] Trial 4 finished with value: 0.7432643201485686 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.0011242212423401743, 'learning_rate_init': 0.0036721153574090387}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:59:05,346] Trial 5 finished with value: 0.7456114715757509 and parameters: {'hidden_layer_sizes': '64', 'activation': 'tanh', 'alpha': 1.908165529742271e-05, 'learning_rate_init': 0.00615721230750478}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:59:15,039] Trial 6 finished with value: 0.7587853557037052 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'alpha': 0.0001441172940129836, 'learning_rate_init': 0.0027235255148231096}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:59:21,500] Trial 7 finished with value: 0.7486486649397751 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 0.00572073368123718, 'learning_rate_init': 0.011422722608597289}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:59:23,074] Trial 8 finished with value: 0.717769498874124 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'tanh', 'alpha': 0.0017082857827447713, 'learning_rate_init': 0.033208008573059715}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:59:25,707] Trial 9 finished with value: 0.6590746885111897 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'tanh', 'alpha': 1.56750266241717e-05, 'learning_rate_init': 0.0002557132639461249}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:59:26,434] Trial 10 finished with value: 0.7465603820348345 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.08860374679542904, 'learning_rate_init': 0.09245755033753394}. Best is trial 1 with value: 0.7648515599116348.
[I 2026-08-15 21:59:35,634] Trial 11 finished with value: 0.7711221812923796 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00018378047545165152, 'learning_rate_init': 0.0017361576702200133}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 21:59:43,721] Trial 12 finished with value: 0.7465735112460008 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00023611039097861603, 'learning_rate_init': 0.0008701283012318942}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 21:59:53,343] Trial 13 finished with value: 0.7407904516916537 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.08480465942561771, 'learning_rate_init': 0.0010046830746537735}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 21:59:54,210] Trial 14 finished with value: 0.7631061918621798 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.0006012581420038722, 'learning_rate_init': 0.014014302297485704}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:03,983] Trial 15 finished with value: 0.7628952231151381 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.003964340549005493, 'learning_rate_init': 0.0021159220290356876}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:05,097] Trial 16 finished with value: 0.7306908661301096 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.00011297336601655877, 'learning_rate_init': 0.0004956900077270401}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:05,641] Trial 17 finished with value: 0.757750302050846 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'relu', 'alpha': 0.037176431176520246, 'learning_rate_init': 0.006829841138609559}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:06,944] Trial 18 finished with value: 0.4340477658106837 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00040661958042475973, 'learning_rate_init': 0.00011202714386233912}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:07,483] Trial 19 finished with value: 0.7514198177612811 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 5.735160151401302e-05, 'learning_rate_init': 0.02132114473137914}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:07,883] Trial 20 finished with value: 0.7519424983423019 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.022935490820225647, 'learning_rate_init': 0.006770203475604916}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:08,264] Trial 21 finished with value: 0.7622358347939743 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.0008184243782881562, 'learning_rate_init': 0.015778887444450572}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:08,573] Trial 22 finished with value: 0.7495770546649363 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.0003498945165345544, 'learning_rate_init': 0.08396972329529079}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:08,988] Trial 23 finished with value: 0.7158613462385802 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.0030887470644294754, 'learning_rate_init': 0.001738797469844686}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:10,165] Trial 24 finished with value: 0.7667038122667756 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 5.003393356465754e-05, 'learning_rate_init': 0.004112912281356308}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:11,297] Trial 25 finished with value: 0.7613338105464089 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 4.309647178358049e-05, 'learning_rate_init': 0.00423739289965536}. Best is trial 11 with value: 0.7711221812923796.
[I 2026-08-15 22:00:13,691] Trial 26 finished with value: 0.7736683086467181 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 2.5036451710770522e-05, 'learning_rate_init': 0.0017663963813750814}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:20,306] Trial 27 finished with value: 0.7442077827012132 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 2.5674432735491156e-05, 'learning_rate_init': 0.0005370892710588369}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:22,568] Trial 28 finished with value: 0.7562439975276944 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 9.228567518752881e-05, 'learning_rate_init': 0.0020588922263503383}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:25,017] Trial 29 finished with value: 0.7640677196566378 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 1.1462344712725405e-05, 'learning_rate_init': 0.0013247623027697524}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:28,086] Trial 30 finished with value: 0.7399919414177745 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 0.00018246098326386043, 'learning_rate_init': 0.0005052125182381104}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:32,580] Trial 31 finished with value: 0.7478582509877647 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 2.9569865062339494e-05, 'learning_rate_init': 0.003975389518092443}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:36,074] Trial 32 finished with value: 0.7398539848124814 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 5.890224614171318e-05, 'learning_rate_init': 0.008770738276523495}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:36,589] Trial 33 finished with value: 0.7284485692727574 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 8.108494621175328e-05, 'learning_rate_init': 0.002939199174167023}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:37,290] Trial 34 finished with value: 0.7000955315752015 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 1.0223073128945045e-05, 'learning_rate_init': 0.0008266786028865722}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:38,058] Trial 35 finished with value: 0.7337255230777426 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'relu', 'alpha': 0.009778493371757423, 'learning_rate_init': 0.0013953729163785893}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:39,984] Trial 36 finished with value: 0.750668768692206 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 3.7583054766604963e-05, 'learning_rate_init': 0.004625398517454182}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:41,303] Trial 37 finished with value: 0.7508498413112474 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 2.1167933470861954e-05, 'learning_rate_init': 0.002935597013461592}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:43,591] Trial 38 finished with value: 0.7270799653408349 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 0.0012991262486498185, 'learning_rate_init': 0.023041624384990134}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:44,083] Trial 39 finished with value: 0.7480307186493944 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.0002285128496712235, 'learning_rate_init': 0.009351104986191782}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:44,686] Trial 40 finished with value: 0.7360247266482127 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 0.044456203277391276, 'learning_rate_init': 0.005098148556083527}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:51,421] Trial 41 finished with value: 0.7619154829570419 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 1.942870497817297e-05, 'learning_rate_init': 0.001287626843426748}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:53,821] Trial 42 finished with value: 0.7489720794932441 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 1.002298744239389e-05, 'learning_rate_init': 0.0022430210690096873}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:00:57,495] Trial 43 finished with value: 0.7321925936998439 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 1.5158071714263655e-05, 'learning_rate_init': 0.00030535357604853777}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:01:00,476] Trial 44 finished with value: 0.7592878590128492 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 3.7535380069966465e-05, 'learning_rate_init': 0.0007288417463233205}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:01:05,563] Trial 45 finished with value: 0.7622693487690888 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 1.492224112590428e-05, 'learning_rate_init': 0.0014117414664632582}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:01:07,086] Trial 46 finished with value: 0.7370532697149044 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'tanh', 'alpha': 6.821965655414989e-05, 'learning_rate_init': 0.0029425982281739084}. Best is trial 26 with value: 0.7736683086467181.
[I 2026-08-15 22:01:08,674] Trial 47 finished with value: 0.7757610434354619 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00010850307311294728, 'learning_rate_init': 0.0015994790774477804}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:09,819] Trial 48 finished with value: 0.7401466772193916 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'alpha': 0.00013549452774420787, 'learning_rate_init': 0.005794716041430986}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:10,425] Trial 49 finished with value: 0.7183768376750033 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 0.0003027018457092866, 'learning_rate_init': 0.0017436664433866627}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:13,492] Trial 50 finished with value: 0.7419348705087173 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0025427255825570326, 'learning_rate_init': 0.003299601963864727}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:15,208] Trial 51 finished with value: 0.7538249988438478 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00934482284771133, 'learning_rate_init': 0.0011155932298924389}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:16,980] Trial 52 finished with value: 0.7411641285732657 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 3.053274575133561e-05, 'learning_rate_init': 0.0006511614271223894}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:20,800] Trial 53 finished with value: 0.7682764194443027 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 4.999390595135873e-05, 'learning_rate_init': 0.00231120770490104}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:21,417] Trial 54 finished with value: 0.7199159445590593 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.0001252817543351595, 'learning_rate_init': 0.0021389257879950233}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:23,819] Trial 55 finished with value: 0.7659531986481372 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 5.505066726150972e-05, 'learning_rate_init': 0.007926299651313536}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:24,858] Trial 56 finished with value: 0.7627034232679651 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0005319245930530962, 'learning_rate_init': 0.007170610575651744}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:26,672] Trial 57 finished with value: 0.7660197000713336 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 5.341312410677244e-05, 'learning_rate_init': 0.0010492153844999543}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:28,861] Trial 58 finished with value: 0.6700194789905174 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00018206906374363023, 'learning_rate_init': 0.0003836156345268264}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:30,593] Trial 59 finished with value: 0.7469648854961832 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 8.277291288873898e-05, 'learning_rate_init': 0.000866403680244506}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:32,118] Trial 60 finished with value: 0.773032551255916 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 4.8317249246333125e-05, 'learning_rate_init': 0.0016461464403419348}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:34,238] Trial 61 finished with value: 0.7727369337362792 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0001012448813091225, 'learning_rate_init': 0.0016689764040489611}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:39,671] Trial 62 finished with value: 0.7709628020143721 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00010744045581105419, 'learning_rate_init': 0.001635520043905778}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:41,173] Trial 63 finished with value: 0.774207404399273 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00011336343942568882, 'learning_rate_init': 0.0016033387785718836}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:43,524] Trial 64 finished with value: 0.746407326007326 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 9.933515756934869e-05, 'learning_rate_init': 0.0015446905876229562}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:44,083] Trial 65 finished with value: 0.7263136090685649 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.0001652952158996193, 'learning_rate_init': 0.0017856378023738192}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:45,753] Trial 66 finished with value: 0.7487357182889136 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00021485435138036713, 'learning_rate_init': 0.0010483998240632712}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:46,470] Trial 67 finished with value: 0.7368838057087752 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'relu', 'alpha': 0.00030536638233096263, 'learning_rate_init': 0.0026371873598236045}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:48,325] Trial 68 finished with value: 0.74649621940469 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0001184696217045581, 'learning_rate_init': 0.000636038400471951}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:50,213] Trial 69 finished with value: 0.773491299781156 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00043282369252091435, 'learning_rate_init': 0.0016869083068035038}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:54,755] Trial 70 finished with value: 0.7517200819037727 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0005229564431946264, 'learning_rate_init': 0.003643380881537365}. Best is trial 47 with value: 0.7757610434354619.
[I 2026-08-15 22:01:56,974] Trial 71 finished with value: 0.7670149552203812 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 8.367400739436532e-05, 'learning_rate_init': 0.0012269701079572213}. Best is trial 47 with value: 0.7757610434354619.

--- ZAKOŃCZONO ---
Najlepsze Accuracy: 0.7764
Najlepsze parametry:
  hidden_layer_sizes: 128_64_32
  activation: relu
  alpha: 4.643799558114539e-05
  learning_rate_init: 0.0016645598304055203

In [115]:
study.trials_dataframe().sort_values(by='value', ascending=False).head(10)

,number,value,datetime_start,datetime_complete,duration,params_activation,params_alpha,params_hidden_layer_sizes,params_learning_rate_init,state
94,94,0.776411,2026-08-15 22:02:36.323532,2026-08-15 22:02:37.962921,0 days 00:00:01.639389,relu,0.000046,128_64_32,0.001665,COMPLETE
89,89,0.776233,2026-08-15 22:02:29.805858,2026-08-15 22:02:31.323679,0 days 00:00:01.517821,relu,0.000143,128_64_32,0.002001,COMPLETE
47,47,0.775761,2026-08-15 22:01:07.087616,2026-08-15 22:01:08.674564,0 days 00:00:01.586948,relu,0.000109,128_64_32,0.001599,COMPLETE
63,63,0.774207,2026-08-15 22:01:39.675018,2026-08-15 22:01:41.173411,0 days 00:00:01.498393,relu,0.000113,128_64_32,0.001603,COMPLETE
26,26,0.773668,2026-08-15 22:00:11.300175,2026-08-15 22:00:13.691278,0 days 00:00:02.391103,tanh,0.000025,128_64_32,0.001766,COMPLETE
69,69,0.773491,2026-08-15 22:01:48.327583,2026-08-15 22:01:50.212969,0 days 00:00:01.885386,relu,0.000433,128_64_32,0.001687,COMPLETE
60,60,0.773033,2026-08-15 22:01:30.596721,2026-08-15 22:01:32.118839,0 days 00:00:01.522118,relu,0.000048,128_64_32,0.001646,COMPLETE
61,61,0.772737,2026-08-15 22:01:32.122829,2026-08-15 22:01:34.238684,0 days 00:00:02.115855,relu,0.000101,128_64_32,0.001669,COMPLETE
81,81,0.772548,2026-08-15 22:02:13.314532,2026-08-15 22:02:14.865226,0 days 00:00:01.550694,relu,0.000736,128_64_32,0.001988,COMPLETE
11,11,0.771122,2026-08-15 21:59:26.438763,2026-08-15 21:59:35.634243,0 days 00:00:09.195480,relu,0.000184,128_64_32,0.001736,COMPLETE

In [116]:
vis.plot_optimization_history(study)

In [117]:
vis.plot_param_importances(study)

In [118]:
vis.plot_parallel_coordinate(study)

# Szukanie hiperparametrów dla KNN

In [119]:
def knn_search(trial):
  n_neighbors = trial.suggest_int('n_neighbors', 1, 50)

  weights = trial.suggest_categorical('weights', ['uniform', 'distance'])

  metric = trial.suggest_categorical('metric', ['euclidean', 'manhattan', 'cosine'])

  knn = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights, metric=metric)

  pipeline = Pipeline([('scaler', StandardScaler()), ('knn', knn)])

  score = cross_val_score(pipeline, X, y, cv=5, scoring='f1').mean()
  return score

study = optuna.create_study(direction='maximize')

study.optimize(knn_search, n_trials=100)

print("\n--- ZAKOŃCZONO ---")
print(f"Najlepsze Accuracy: {study.best_value:.4f}")
print("Najlepsze parametry:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

[I 2026-08-15 22:02:52,189] A new study created in memory with name: no-name-c6901235-bd31-475a-8550-684692f7a25d
[I 2026-08-15 22:02:52,305] Trial 0 finished with value: 0.7037843134214061 and parameters: {'n_neighbors': 50, 'weights': 'uniform', 'metric': 'cosine'}. Best is trial 0 with value: 0.7037843134214061.
[I 2026-08-15 22:02:52,422] Trial 1 finished with value: 0.719944108362843 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'metric': 'cosine'}. Best is trial 1 with value: 0.719944108362843.
[I 2026-08-15 22:02:52,532] Trial 2 finished with value: 0.7338406025535542 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'metric': 'cosine'}. Best is trial 2 with value: 0.7338406025535542.
[I 2026-08-15 22:02:52,655] Trial 3 finished with value: 0.7078909491152315 and parameters: {'n_neighbors': 30, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 2 with value: 0.7338406025535542.
[I 2026-08-15 22:02:52,802] Trial 4 finished with value: 0.7193010892149382 and parameters: {'n_neighbors': 45, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 2 with value: 0.7338406025535542.
[I 2026-08-15 22:02:52,964] Trial 5 finished with value: 0.6979627530343911 and parameters: {'n_neighbors': 47, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 2 with value: 0.7338406025535542.
[I 2026-08-15 22:02:53,164] Trial 6 finished with value: 0.7515281238308986 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:53,421] Trial 7 finished with value: 0.7165816997734228 and parameters: {'n_neighbors': 37, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:53,566] Trial 8 finished with value: 0.7268337835283063 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:53,863] Trial 9 finished with value: 0.719522740033689 and parameters: {'n_neighbors': 42, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:53,979] Trial 10 finished with value: 0.7491171461577957 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:54,090] Trial 11 finished with value: 0.7491171461577957 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:54,247] Trial 12 finished with value: 0.7484268410031351 and parameters: {'n_neighbors': 23, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:54,460] Trial 13 finished with value: 0.685959743320309 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:54,617] Trial 14 finished with value: 0.7461199617665446 and parameters: {'n_neighbors': 26, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:55,229] Trial 15 finished with value: 0.7457098650770637 and parameters: {'n_neighbors': 36, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:55,834] Trial 16 finished with value: 0.7346334110982122 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:56,178] Trial 17 finished with value: 0.7268337835283063 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:56,336] Trial 18 finished with value: 0.7484268410031351 and parameters: {'n_neighbors': 23, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:56,480] Trial 19 finished with value: 0.7462193362193362 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 6 with value: 0.7515281238308986.
[I 2026-08-15 22:02:56,596] Trial 20 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:56,704] Trial 21 finished with value: 0.7493319313097163 and parameters: {'n_neighbors': 29, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:56,814] Trial 22 finished with value: 0.7515281238308986 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:56,926] Trial 23 finished with value: 0.7452921637845004 and parameters: {'n_neighbors': 35, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:57,034] Trial 24 finished with value: 0.737791109918054 and parameters: {'n_neighbors': 40, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:57,144] Trial 25 finished with value: 0.7515281238308986 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:57,254] Trial 26 finished with value: 0.7461199617665446 and parameters: {'n_neighbors': 26, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:57,369] Trial 27 finished with value: 0.746361022982856 and parameters: {'n_neighbors': 33, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:57,589] Trial 28 finished with value: 0.719376754632229 and parameters: {'n_neighbors': 40, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:57,767] Trial 29 finished with value: 0.7427619803259852 and parameters: {'n_neighbors': 27, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:58,029] Trial 30 finished with value: 0.7215896807265839 and parameters: {'n_neighbors': 50, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:58,202] Trial 31 finished with value: 0.746361022982856 and parameters: {'n_neighbors': 33, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:58,325] Trial 32 finished with value: 0.746361022982856 and parameters: {'n_neighbors': 33, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:58,445] Trial 33 finished with value: 0.7484268410031351 and parameters: {'n_neighbors': 23, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:58,561] Trial 34 finished with value: 0.74113751570095 and parameters: {'n_neighbors': 29, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:58,740] Trial 35 finished with value: 0.7338406025535542 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'metric': 'cosine'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:58,896] Trial 36 finished with value: 0.737791109918054 and parameters: {'n_neighbors': 40, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:59,043] Trial 37 finished with value: 0.7193010892149382 and parameters: {'n_neighbors': 45, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:59,169] Trial 38 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:59,466] Trial 39 finished with value: 0.7112009216527314 and parameters: {'n_neighbors': 28, 'weights': 'uniform', 'metric': 'cosine'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:59,597] Trial 40 finished with value: 0.7479840421016892 and parameters: {'n_neighbors': 35, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:59,678] Trial 41 finished with value: 0.750459264632543 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:59,781] Trial 42 finished with value: 0.7515281238308986 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:59,866] Trial 43 finished with value: 0.7420392707651191 and parameters: {'n_neighbors': 24, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:02:59,952] Trial 44 finished with value: 0.7398905959024612 and parameters: {'n_neighbors': 39, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,036] Trial 45 finished with value: 0.7400426041944719 and parameters: {'n_neighbors': 43, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,118] Trial 46 finished with value: 0.7467260875584374 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,203] Trial 47 finished with value: 0.7320032170317737 and parameters: {'n_neighbors': 35, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,281] Trial 48 finished with value: 0.745467596121067 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,360] Trial 49 finished with value: 0.7438554685066858 and parameters: {'n_neighbors': 38, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,438] Trial 50 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,522] Trial 51 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,599] Trial 52 finished with value: 0.7493319313097163 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,679] Trial 53 finished with value: 0.750459264632543 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,771] Trial 54 finished with value: 0.7463401700999449 and parameters: {'n_neighbors': 34, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,854] Trial 55 finished with value: 0.7520493482582941 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:00,941] Trial 56 finished with value: 0.7328101929080358 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,019] Trial 57 finished with value: 0.7520493482582941 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,096] Trial 58 finished with value: 0.7346334110982122 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,175] Trial 59 finished with value: 0.7520493482582941 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,286] Trial 60 finished with value: 0.7127403345726419 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,387] Trial 61 finished with value: 0.7520493482582941 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,466] Trial 62 finished with value: 0.7520493482582941 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,543] Trial 63 finished with value: 0.7404442477658542 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,620] Trial 64 finished with value: 0.7325012138547518 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,694] Trial 65 finished with value: 0.7130534121548818 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,772] Trial 66 finished with value: 0.745467596121067 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,862] Trial 67 finished with value: 0.7465159003348388 and parameters: {'n_neighbors': 22, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:01,941] Trial 68 finished with value: 0.7491171461577957 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,022] Trial 69 finished with value: 0.729328855445911 and parameters: {'n_neighbors': 27, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,105] Trial 70 finished with value: 0.7144172739887438 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,187] Trial 71 finished with value: 0.7520493482582941 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,265] Trial 72 finished with value: 0.7324909106116783 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,346] Trial 73 finished with value: 0.7484268410031351 and parameters: {'n_neighbors': 23, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,424] Trial 74 finished with value: 0.7461199617665446 and parameters: {'n_neighbors': 26, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,503] Trial 75 finished with value: 0.7467260875584374 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,609] Trial 76 finished with value: 0.7060846625711926 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,710] Trial 77 finished with value: 0.7493319313097163 and parameters: {'n_neighbors': 29, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,786] Trial 78 finished with value: 0.7346334110982122 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,882] Trial 79 finished with value: 0.7309829178782026 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:02,957] Trial 80 finished with value: 0.7420392707651191 and parameters: {'n_neighbors': 24, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,034] Trial 81 finished with value: 0.7520493482582941 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,108] Trial 82 finished with value: 0.7465159003348388 and parameters: {'n_neighbors': 22, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,187] Trial 83 finished with value: 0.7404442477658542 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,265] Trial 84 finished with value: 0.7493066643129044 and parameters: {'n_neighbors': 27, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,341] Trial 85 finished with value: 0.7520493482582941 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,421] Trial 86 finished with value: 0.745467596121067 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,506] Trial 87 finished with value: 0.7339898419321962 and parameters: {'n_neighbors': 48, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,601] Trial 88 finished with value: 0.7462193362193362 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,704] Trial 89 finished with value: 0.7208568831272829 and parameters: {'n_neighbors': 34, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,801] Trial 90 finished with value: 0.7491171461577957 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,888] Trial 91 finished with value: 0.7520493482582941 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:03,973] Trial 92 finished with value: 0.7465159003348388 and parameters: {'n_neighbors': 22, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:04,053] Trial 93 finished with value: 0.7410560510564397 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.
[I 2026-08-15 22:03:04,130] Trial 94 finished with value: 0.7404442477658542 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 20 with value: 0.7525459355357332.

--- ZAKOŃCZONO ---
Najlepsze Accuracy: 0.7525
Najlepsze parametry:
  n_neighbors: 31
  weights: distance
  metric: euclidean

In [120]:
study.trials_dataframe().sort_values(by='value', ascending=False).head(10)

,number,value,datetime_start,datetime_complete,duration,params_metric,params_n_neighbors,params_weights,state
20,20,0.752546,2026-08-15 22:02:56.483588,2026-08-15 22:02:56.596277,0 days 00:00:00.112689,euclidean,31,distance,COMPLETE
51,51,0.752546,2026-08-15 22:03:00.439492,2026-08-15 22:03:00.522828,0 days 00:00:00.083336,euclidean,31,distance,COMPLETE
50,50,0.752546,2026-08-15 22:03:00.361539,2026-08-15 22:03:00.438249,0 days 00:00:00.076710,euclidean,31,distance,COMPLETE
38,38,0.752546,2026-08-15 22:02:59.044353,2026-08-15 22:02:59.169720,0 days 00:00:00.125367,euclidean,31,distance,COMPLETE
55,55,0.752049,2026-08-15 22:03:00.774706,2026-08-15 22:03:00.854054,0 days 00:00:00.079348,euclidean,21,distance,COMPLETE
57,57,0.752049,2026-08-15 22:03:00.942663,2026-08-15 22:03:01.019505,0 days 00:00:00.076842,euclidean,21,distance,COMPLETE
59,59,0.752049,2026-08-15 22:03:01.097607,2026-08-15 22:03:01.175834,0 days 00:00:00.078227,euclidean,21,distance,COMPLETE
61,61,0.752049,2026-08-15 22:03:01.289807,2026-08-15 22:03:01.387505,0 days 00:00:00.097698,euclidean,21,distance,COMPLETE
71,71,0.752049,2026-08-15 22:03:02.106512,2026-08-15 22:03:02.187556,0 days 00:00:00.081044,euclidean,21,distance,COMPLETE
81,81,0.752049,2026-08-15 22:03:02.958721,2026-08-15 22:03:03.034394,0 days 00:00:00.075673,euclidean,21,distance,COMPLETE

In [121]:
vis.plot_optimization_history(study)

In [122]:
vis.plot_param_importances(study)

In [123]:
vis.plot_parallel_coordinate(study)

# Moje szanse na tytaniku 💀

In [124]:
print(titanic_df.columns)
titanic_df.head()

Index(['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'FamilySize', 'IsAlone',
       'Embarked_Q', 'Embarked_S', 'Cabin_B', 'Cabin_C', 'Cabin_D', 'Cabin_E',
       'Cabin_F', 'Cabin_G', 'Cabin_T', 'Cabin_Unknown', 'Title_Miss',
       'Title_Mr', 'Title_Mrs', 'Title_Rare'],
      dtype='object')

,Survived,Pclass,Sex,Age,Fare,FamilySize,IsAlone,Embarked_Q,Embarked_S,Cabin_B,...,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Cabin_Unknown,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
PassengerId,,,,,,,,,,,,,,,,,,,,,
1,0,3,0,22.0,7.2500,2,0,0,1,0,...,0,0,0,0,0,1,0,1,0,0
2,1,1,1,38.0,71.2833,2,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,3,1,26.0,7.9250,1,1,0,1,0,...,0,0,0,0,0,1,1,0,0,0
4,1,1,1,35.0,53.1000,2,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
5,0,3,0,35.0,8.0500,1,1,0,1,0,...,0,0,0,0,0,1,0,1,0,0

In [125]:
ja = pd.DataFrame([{
    'Pclass': 1,
    'Sex': 0,
    'Age': 21.0,
    'Fare': 53.0,
    'FamilySize': 2,
    'IsAlone': 0,
    'Embarked_Q': 1,
    'Embarked_S': 0,
    'Cabin_B': 0,
    'Cabin_C': 0,
    'Cabin_D': 0,
    'Cabin_E': 0,
    'Cabin_F': 0,
    'Cabin_G': 0,
    'Cabin_T': 0,
    'Cabin_Unknown': 0,
    'Title_Miss': 0,
    'Title_Mr': 1,
    'Title_Mrs': 0,
    'Title_Rare': 0
}])

# użyje dobrych parametrów
  # * wartości mogą się różnić bo raczej odpale cały plik jak skończę
svm = SVC(kernel='rbf', C=7.925165, gamma=0.012747, class_weight=None)
svm.fit(X_train_scaled, y_train)

mlp = MLPClassifier(max_iter=1000, random_state=42, hidden_layer_sizes=(128, 64, 32), alpha=0.000312, learning_rate_init=0.001695, early_stopping=True)
mlp.fit(X_train_scaled, y_train)

knn = KNeighborsClassifier(n_neighbors=31, metric='euclidean', weights='distance')
knn.fit(X_train_scaled, y_train)

ja_scaled = scaler.transform(ja)

svm_pred = svm.predict(ja_scaled)
mlp_pred = mlp.predict(ja_scaled)
knn_pred = knn.predict(ja_scaled)

for pred in [svm_pred, mlp_pred, knn_pred]:
  if pred[0] == 1:
    print('Żyje!!!')
  else:
    print('GG')

GG
Żyje!!!
GG

# Wnioski
* niestety wygląda na to, że nie przeżyłbym na tytaniku, a przynajmniej 2 na 3 modele tak zdecydowały (mimo, że dałem sobie 1 klasę)
* wszystkie 3 modele pokonały model bazowy
* wszystkie 3 modele osiągnęły bardzo podobny poziom
* poprawność przewidywania jest znacząco zależna od tego jakie dane wylosują się jako treningowe